import { completeThemeTokens, type ThemeFamily } from '../themeTypes';
import { resolveCodeThemeTokens } from '../codeSyntax';

export const BUILTIN_AURORA_BOREAL: ThemeFamily = {
  schemaVersion: 2,
  id: "aurora-boreal",
  name: "Aurora Boreal",
  aliases: ["builtin-aurora-boreal"],
  builtIn: true,
  variants: {
    light: {
      tokens: completeThemeTokens('light', {
      accent: "#5af2b2",
      background: "#8ad1ea",
      surface: "#96d6c7",
      surfaceElevated: "#94cec1",
      surfaceMuted: "#92e0c7",
      border: "#96c5bc",
      borderStrong: "#8cbcb2",
      textPrimary: "#e2f5f8",
      textSecondary: "#a7d1cd",
      textMuted: "#77a19a",
      foreground: "#e2f5f8",
      foregroundMuted: "#a7d1cd",
      foregroundSubtle: "#77a19a",
      accentHover: "#89f5d1",
      accentForeground: "#8ad1ea",
      success: "#47c77d",
      successForeground: "#8ad1ea",
      warning: "#e39a26",
      warningForeground: "#8ad1ea",
      danger: "#da5649",
      dangerForeground: "#8ad1ea",
      info: "#4196ce",
      inputBackground: "#94cec1",
      inputForeground: "#e2f5f8",
      placeholder: "#77a19a",
      disabledForeground: "#77a19a",
      buttonPrimaryBackground: "#5af2b2",
      buttonPrimaryForeground: "#8ad1ea",
      buttonSecondaryBackground: "#94cec1",
      buttonSecondaryForeground: "#e2f5f8",
      link: "#4196ce",
      focusRing: "#5af2b2",
      selectionBackground: "#5af2b2",
      selectionForeground: "#8ad1ea",
      overlay: "rgba(2, 16, 21, 0.7)",
      glow: "rgba(77, 255, 180, 0.25)",
      }),
      code: { preset: 'aurora-boreal', tokens: resolveCodeThemeTokens('aurora-boreal', 'light') },
    },
    dark: {
      tokens: completeThemeTokens('dark', {
      accent: "#4dffb4",
      background: "#021015",
      surface: "#0a1f1a",
      surfaceElevated: "#122e28",
      surfaceMuted: "#051812",
      border: "#1a3530",
      borderStrong: "#2a5048",
      textPrimary: "#e0f7fa",
      textSecondary: "#a3d5d0",
      textMuted: "#5a8a82",
      foreground: "#e0f7fa",
      foregroundMuted: "#a3d5d0",
      foregroundSubtle: "#5a8a82",
      accentHover: "#7fffd4",
      accentForeground: "#021015",
      success: "#2ecc71",
      successForeground: "#021015",
      warning: "#f39c12",
      warningForeground: "#021015",
      danger: "#e74c3c",
      dangerForeground: "#021015",
      info: "#3498db",
      inputBackground: "#122e28",
      inputForeground: "#e0f7fa",
      placeholder: "#5a8a82",
      disabledForeground: "#5a8a82",
      buttonPrimaryBackground: "#4dffb4",
      buttonPrimaryForeground: "#021015",
      buttonSecondaryBackground: "#122e28",
      buttonSecondaryForeground: "#e0f7fa",
      link: "#3498db",
      focusRing: "#4dffb4",
      selectionBackground: "#4dffb4",
      selectionForeground: "#021015",
      overlay: "rgba(2, 16, 21, 0.7)",
      glow: "rgba(77, 255, 180, 0.25)",
      }),
      code: { preset: 'aurora-boreal', tokens: resolveCodeThemeTokens('aurora-boreal', 'dark') },
    },
  },
};
