import { completeThemeTokens, type ThemeFamily } from '../themeTypes';
import { resolveCodeThemeTokens } from '../codeSyntax';

export const BUILTIN_CATPPUCCIN: ThemeFamily = {
  schemaVersion: 2,
  id: "catppuccin",
  name: "Forge Catppuccin",
  aliases: ["builtin-catppuccin"],
  builtIn: true,
  variants: {
    light: {
      tokens: completeThemeTokens('light', {
      background: "#a0a0bd",
      surface: "#989ab1",
      surfaceElevated: "#9092a7",
      border: "#7e8194",
      textPrimary: "#d0d8f1",
      textSecondary: "#a9afc5",
      textMuted: "#8e93a8",
      accent: "#eb93ab",
      accentHover: "#f1b590",
      accentForeground: "#a0a0bd",
      success: "#aadea6",
      warning: "#f3e0b5",
      danger: "#eb93ab",
      info: "#90d7e4",
      focusRing: "#eb93ab",
      overlay: "rgba(0, 0, 0, 0.6)",
      glow: "rgba(243, 139, 168, 0.25)",
      surfaceMuted: "#a3a3c0",
      borderStrong: "#d0d8f1",
      }),
      code: { preset: 'catppuccin', tokens: resolveCodeThemeTokens('catppuccin', 'light') },
    },
    dark: {
      tokens: completeThemeTokens('dark', {
      background: "#1e1e2e",
      surface: "#313244",
      surfaceElevated: "#45475a",
      border: "#6c7086",
      textPrimary: "#cdd6f4",
      textSecondary: "#a6adc8",
      textMuted: "#8c91aa",
      accent: "#f38ba8",
      accentHover: "#fab387",
      accentForeground: "#1e1e2e",
      success: "#a6e3a1",
      warning: "#f9e2af",
      danger: "#f38ba8",
      info: "#89dceb",
      focusRing: "#f38ba8",
      overlay: "rgba(0, 0, 0, 0.6)",
      glow: "rgba(243, 139, 168, 0.25)",
      surfaceMuted: "#181825",
      borderStrong: "#cdd6f4",
      }),
      code: { preset: 'catppuccin', tokens: resolveCodeThemeTokens('catppuccin', 'dark') },
    },
  },
};
