import { completeThemeTokens, type ThemeFamily } from '../themeTypes';
import { resolveCodeThemeTokens } from '../codeSyntax';

export const BUILTIN_CIRCUIT_MINT: ThemeFamily = {
  schemaVersion: 2,
  id: "circuit-mint",
  name: "Circuit Mint",
  aliases: ["builtin-circuit-mint"],
  builtIn: true,
  variants: {
    light: {
      tokens: completeThemeTokens('light', {
      accent: "#77deb5",
      background: "#afbec2",
      surface: "#a8b9be",
      surfaceElevated: "#a2b5ba",
      surfaceMuted: "#aabcc2",
      border: "#9badb3",
      borderStrong: "#8d9fa4",
      textPrimary: "#e9f4f0",
      textSecondary: "#b0c2be",
      textMuted: "#7d918d",
      foreground: "#e9f4f0",
      foregroundMuted: "#b0c2be",
      foregroundSubtle: "#7d918d",
      accentHover: "#93e8c7",
      accentForeground: "#afbec2",
      success: "#68cd8c",
      successForeground: "#afbec2",
      warning: "#e4bd59",
      warningForeground: "#afbec2",
      danger: "#e67575",
      dangerForeground: "#afbec2",
      info: "#87d0f2",
      inputBackground: "#a2b5ba",
      inputForeground: "#e9f4f0",
      placeholder: "#7d918d",
      disabledForeground: "#7d918d",
      buttonPrimaryBackground: "#77deb5",
      buttonPrimaryForeground: "#afbec2",
      buttonSecondaryBackground: "#a2b5ba",
      buttonSecondaryForeground: "#e9f4f0",
      link: "#87d0f2",
      focusRing: "#77deb5",
      selectionBackground: "#77deb5",
      selectionForeground: "#afbec2",
      overlay: "rgba(13, 17, 18, 0.7)",
      glow: "rgba(110, 231, 183, 0.25)",
      }),
      code: { preset: 'circuit-mint', tokens: resolveCodeThemeTokens('circuit-mint', 'light') },
    },
    dark: {
      tokens: completeThemeTokens('dark', {
      accent: "#6ee7b7",
      background: "#0d1112",
      surface: "#161d1f",
      surfaceElevated: "#1f292c",
      surfaceMuted: "#111719",
      border: "#2d3a3e",
      borderStrong: "#4a5c61",
      textPrimary: "#e8f5f0",
      textSecondary: "#aec4bf",
      textMuted: "#718984",
      foreground: "#e8f5f0",
      foregroundMuted: "#aec4bf",
      foregroundSubtle: "#718984",
      accentHover: "#8befc9",
      accentForeground: "#0d1112",
      success: "#5fd68a",
      successForeground: "#0d1112",
      warning: "#f0c24d",
      warningForeground: "#0d1112",
      danger: "#f06b6b",
      dangerForeground: "#0d1112",
      info: "#7dd3fc",
      inputBackground: "#1f292c",
      inputForeground: "#e8f5f0",
      placeholder: "#718984",
      disabledForeground: "#718984",
      buttonPrimaryBackground: "#6ee7b7",
      buttonPrimaryForeground: "#0d1112",
      buttonSecondaryBackground: "#1f292c",
      buttonSecondaryForeground: "#e8f5f0",
      link: "#7dd3fc",
      focusRing: "#6ee7b7",
      selectionBackground: "#6ee7b7",
      selectionForeground: "#0d1112",
      overlay: "rgba(13, 17, 18, 0.7)",
      glow: "rgba(110, 231, 183, 0.25)",
      }),
      code: { preset: 'circuit-mint', tokens: resolveCodeThemeTokens('circuit-mint', 'dark') },
    },
  },
};
