import { completeThemeTokens, type ThemeFamily } from '../themeTypes';
import { resolveCodeThemeTokens } from '../codeSyntax';

export const BUILTIN_COTTON_CANDY_CONSOLE: ThemeFamily = {
  schemaVersion: 2,
  id: "cotton-candy-console",
  name: "Cotton Candy Console",
  aliases: ["builtin-cotton-candy-console","cotton-candy-console"],
  builtIn: true,
  variants: {
    light: {
      tokens: completeThemeTokens('light', {
      accent: "#7FB8C7",
      background: "#EAF3F5",
      surface: "#F3EDEB",
      surfaceElevated: "#FFFFFF",
      surfaceMuted: "#EBD0D7",
      border: "#B7C9D3",
      borderStrong: "#869CB1",
      textPrimary: "#412A3A",
      textSecondary: "#574457",
      textMuted: "#614E61",
      foreground: "#412A3A",
      foregroundMuted: "#574457",
      foregroundSubtle: "#614E61",
      accentHover: "#69A7B7",
      accentForeground: "#1F141C",
      success: "#2D7A5C",
      successForeground: "#FFFFFF",
      warning: "#A35C2B",
      warningForeground: "#FFFFFF",
      danger: "#AA5B6E",
      dangerForeground: "#FFFFFF",
      info: "#415C73",
      inputBackground: "#FFFFFF",
      inputForeground: "#412A3A",
      placeholder: "#614E61",
      disabledForeground: "#614E61",
      buttonPrimaryBackground: "#7FB8C7",
      buttonPrimaryForeground: "#1F141C",
      buttonSecondaryBackground: "#EBD0D7",
      buttonSecondaryForeground: "#412A3A",
      link: "#3B6B80",
      focusRing: "#AA5B6E",
      selectionBackground: "#D6E9ED",
      selectionForeground: "#412A3A",
      overlay: "rgba(65, 42, 58, 0.4)",
      glow: "rgba(127, 184, 199, 0.25)",
      }),
      code: { preset: 'cotton-candy-console', tokens: resolveCodeThemeTokens('cotton-candy-console', 'light') },
    },
    dark: {
      tokens: completeThemeTokens('dark', {
      accent: "#447f8e",
      background: "#30555d",
      surface: "#573f37",
      surfaceElevated: "#404040",
      surfaceMuted: "#6b3241",
      border: "#465f6d",
      borderStrong: "#576d82",
      textPrimary: "#402b3a",
      textSecondary: "#564556",
      textMuted: "#604f60",
      foreground: "#402b3a",
      foregroundMuted: "#564556",
      foregroundSubtle: "#604f60",
      accentHover: "#4e8796",
      accentForeground: "#1e151c",
      success: "#31765b",
      successForeground: "#404040",
      warning: "#9d5d31",
      warningForeground: "#404040",
      danger: "#9a5666",
      dangerForeground: "#404040",
      info: "#435c71",
      inputBackground: "#404040",
      inputForeground: "#402b3a",
      placeholder: "#604f60",
      disabledForeground: "#604f60",
      buttonPrimaryBackground: "#447f8e",
      buttonPrimaryForeground: "#1e151c",
      buttonSecondaryBackground: "#6b3241",
      buttonSecondaryForeground: "#402b3a",
      link: "#3e6a7d",
      focusRing: "#9a5666",
      selectionBackground: "#325f68",
      selectionForeground: "#402b3a",
      overlay: "rgba(65, 42, 58, 0.4)",
      glow: "rgba(127, 184, 199, 0.25)",
      }),
      code: { preset: 'cotton-candy-console', tokens: resolveCodeThemeTokens('cotton-candy-console', 'dark') },
    },
  },
};
