import { completeThemeTokens, type ThemeFamily } from '../themeTypes';

export const BUILTIN_CYBER_ORCHID: ThemeFamily = {
  schemaVersion: 2,
  id: "cyber-orchid",
  name: "Cyber Orchid",
  aliases: ["builtin-cyber-orchid"],
  builtIn: true,
  variants: {
    light: {
      tokens: completeThemeTokens('light', {
      accent: "#c08df3",
      background: "#bf9cd7",
      surface: "#b19bcb",
      surfaceElevated: "#aa98c3",
      surfaceMuted: "#b3a1cb",
      border: "#a493b7",
      borderStrong: "#9689a4",
      textPrimary: "#f3eafd",
      textSecondary: "#d4c7e5",
      textMuted: "#9a8dad",
      foreground: "#f3eafd",
      foregroundMuted: "#d4c7e5",
      foregroundSubtle: "#9a8dad",
      accentHover: "#d7aff8",
      accentForeground: "#bf9cd7",
      success: "#8ee7ae",
      successForeground: "#bf9cd7",
      warning: "#efd755",
      warningForeground: "#bf9cd7",
      danger: "#ee7b7b",
      dangerForeground: "#bf9cd7",
      info: "#9bc5f5",
      inputBackground: "#aa98c3",
      inputForeground: "#f3eafd",
      placeholder: "#9a8dad",
      disabledForeground: "#9a8dad",
      buttonPrimaryBackground: "#c08df3",
      buttonPrimaryForeground: "#bf9cd7",
      buttonSecondaryBackground: "#aa98c3",
      buttonSecondaryForeground: "#f3eafd",
      link: "#9bc5f5",
      focusRing: "#c08df3",
      selectionBackground: "#c08df3",
      selectionForeground: "#bf9cd7",
      overlay: "rgba(13, 6, 18, 0.7)",
      glow: "rgba(192, 132, 252, 0.25)",
      }),
    },
    dark: {
      tokens: completeThemeTokens('dark', {
      accent: "#c084fc",
      background: "#0d0612",
      surface: "#1a1125",
      surfaceElevated: "#271c35",
      surfaceMuted: "#140e1c",
      border: "#3a2d48",
      borderStrong: "#5a4d68",
      textPrimary: "#f3e8ff",
      textSecondary: "#d4c4e8",
      textMuted: "#9a8ab0",
      foreground: "#f3e8ff",
      foregroundMuted: "#d4c4e8",
      foregroundSubtle: "#9a8ab0",
      accentHover: "#d8a8ff",
      accentForeground: "#0d0612",
      success: "#86efac",
      successForeground: "#0d0612",
      warning: "#fde047",
      warningForeground: "#0d0612",
      danger: "#f87171",
      dangerForeground: "#0d0612",
      info: "#93c5fd",
      inputBackground: "#271c35",
      inputForeground: "#f3e8ff",
      placeholder: "#9a8ab0",
      disabledForeground: "#9a8ab0",
      buttonPrimaryBackground: "#c084fc",
      buttonPrimaryForeground: "#0d0612",
      buttonSecondaryBackground: "#271c35",
      buttonSecondaryForeground: "#f3e8ff",
      link: "#93c5fd",
      focusRing: "#c084fc",
      selectionBackground: "#c084fc",
      selectionForeground: "#0d0612",
      overlay: "rgba(13, 6, 18, 0.7)",
      glow: "rgba(192, 132, 252, 0.25)",
      }),
    },
  },
};
