import { completeThemeTokens, type ThemeFamily } from '../themeTypes';
import { resolveCodeThemeTokens } from '../codeSyntax';

export const BUILTIN_EMBER_MONASTERY: ThemeFamily = {
  schemaVersion: 2,
  id: "ember-monastery",
  name: "Ember Monastery",
  aliases: ["builtin-ember-monastery"],
  builtIn: true,
  variants: {
    light: {
      tokens: completeThemeTokens('light', {
      accent: "#f1754e",
      background: "#c9b0a4",
      surface: "#c3aa9e",
      surfaceElevated: "#b7a59c",
      surfaceMuted: "#c4b1a2",
      border: "#ad9e97",
      borderStrong: "#9c918b",
      textPrimary: "#f2e6d6",
      textSecondary: "#d1c0ab",
      textMuted: "#97887b",
      foreground: "#f2e6d6",
      foregroundMuted: "#d1c0ab",
      foregroundSubtle: "#97887b",
      accentHover: "#f39166",
      accentForeground: "#c9b0a4",
      success: "#86c289",
      successForeground: "#c9b0a4",
      warning: "#f2b45a",
      warningForeground: "#c9b0a4",
      danger: "#dc7c7c",
      dangerForeground: "#c9b0a4",
      info: "#6fb4eb",
      inputBackground: "#b7a59c",
      inputForeground: "#f2e6d6",
      placeholder: "#97887b",
      disabledForeground: "#97887b",
      buttonPrimaryBackground: "#f1754e",
      buttonPrimaryForeground: "#c9b0a4",
      buttonSecondaryBackground: "#b7a59c",
      buttonSecondaryForeground: "#f2e6d6",
      link: "#6fb4eb",
      focusRing: "#f1754e",
      selectionBackground: "#f1754e",
      selectionForeground: "#c9b0a4",
      overlay: "rgba(26, 18, 14, 0.7)",
      glow: "rgba(255, 110, 64, 0.25)",
      }),
      code: { preset: 'ember-monastery', tokens: resolveCodeThemeTokens('ember-monastery', 'light') },
    },
    dark: {
      tokens: completeThemeTokens('dark', {
      accent: "#ff6e40",
      background: "#1a120e",
      surface: "#2a1e18",
      surfaceElevated: "#3a2e28",
      surfaceMuted: "#221a14",
      border: "#4a3e38",
      borderStrong: "#6a5e58",
      textPrimary: "#f5e6d3",
      textSecondary: "#d4c0a8",
      textMuted: "#9a8878",
      foreground: "#f5e6d3",
      foregroundMuted: "#d4c0a8",
      foregroundSubtle: "#9a8878",
      accentHover: "#ff8c5a",
      accentForeground: "#1a120e",
      success: "#81c784",
      successForeground: "#1a120e",
      warning: "#ffb74d",
      warningForeground: "#1a120e",
      danger: "#e57373",
      dangerForeground: "#1a120e",
      info: "#64b5f6",
      inputBackground: "#3a2e28",
      inputForeground: "#f5e6d3",
      placeholder: "#9a8878",
      disabledForeground: "#9a8878",
      buttonPrimaryBackground: "#ff6e40",
      buttonPrimaryForeground: "#1a120e",
      buttonSecondaryBackground: "#3a2e28",
      buttonSecondaryForeground: "#f5e6d3",
      link: "#64b5f6",
      focusRing: "#ff6e40",
      selectionBackground: "#ff6e40",
      selectionForeground: "#1a120e",
      overlay: "rgba(26, 18, 14, 0.7)",
      glow: "rgba(255, 110, 64, 0.25)",
      }),
      code: { preset: 'ember-monastery', tokens: resolveCodeThemeTokens('ember-monastery', 'dark') },
    },
  },
};
