import { completeThemeTokens, type ThemeFamily } from '../themeTypes';
import { resolveCodeThemeTokens } from '../codeSyntax';

export const BUILTIN_GITHUB_LIGHT: ThemeFamily = {
  schemaVersion: 2,
  id: "github-light",
  name: "Forge GitHub Light",
  aliases: ["builtin-github-light"],
  builtIn: true,
  variants: {
    light: {
      tokens: completeThemeTokens('light', {
      background: "#ffffff",
      surface: "#f6f8fa",
      surfaceElevated: "#ffffff",
      border: "#d0d7de",
      textPrimary: "#24292f",
      textSecondary: "#57606a",
      textMuted: "#656d76",
      accent: "#0969da",
      accentHover: "#0550ae",
      accentForeground: "#ffffff",
      success: "#1a7f37",
      warning: "#7a5200",
      danger: "#cf222e",
      info: "#0969da",
      focusRing: "#0969da",
      overlay: "rgba(0, 0, 0, 0.25)",
      glow: "rgba(9, 105, 218, 0.18)",
      surfaceMuted: "#ebeef1",
      borderStrong: "#6e7781",
      placeholder: "#57606a",
      disabledForeground: "#6e7781",
      }),
      code: { preset: 'github-light', tokens: resolveCodeThemeTokens('github-light', 'light') },
    },
    dark: {
      tokens: completeThemeTokens('dark', {
      background: "#404040",
      surface: "#324354",
      surfaceElevated: "#404040",
      border: "#45525f",
      textPrimary: "#25292e",
      textSecondary: "#586069",
      textMuted: "#666d75",
      accent: "#136ad0",
      accentHover: "#0d51a6",
      accentForeground: "#404040",
      success: "#1f7a39",
      warning: "#745006",
      danger: "#c62b35",
      info: "#136ad0",
      focusRing: "#136ad0",
      overlay: "rgba(0, 0, 0, 0.25)",
      glow: "rgba(9, 105, 218, 0.18)",
      surfaceMuted: "#3c4753",
      borderStrong: "#6f7780",
      placeholder: "#586069",
      disabledForeground: "#6f7780",
      }),
      code: { preset: 'github-light', tokens: resolveCodeThemeTokens('github-light', 'dark') },
    },
  },
};
