import { completeThemeTokens, type ThemeFamily } from '../themeTypes';
import { resolveCodeThemeTokens } from '../codeSyntax';

export const BUILTIN_GLACIAL_INK: ThemeFamily = {
  schemaVersion: 2,
  id: "glacial-ink",
  name: "Glacial Ink",
  aliases: ["builtin-glacial-ink"],
  builtIn: true,
  variants: {
    light: {
      tokens: completeThemeTokens('light', {
      accent: "#1fd8ed",
      background: "#91b2d5",
      surface: "#94aac5",
      surfaceElevated: "#92a4ba",
      surfaceMuted: "#93aecc",
      border: "#8e9daf",
      borderStrong: "#838f9d",
      textPrimary: "#e2f5f8",
      textSecondary: "#a5cedb",
      textMuted: "#6c8ca0",
      foreground: "#e2f5f8",
      foregroundMuted: "#a5cedb",
      foregroundSubtle: "#6c8ca0",
      accentHover: "#42dff0",
      accentForeground: "#91b2d5",
      success: "#73e6ae",
      successForeground: "#91b2d5",
      warning: "#f1cf4e",
      warningForeground: "#91b2d5",
      danger: "#f25f5f",
      dangerForeground: "#91b2d5",
      info: "#4ebff1",
      inputBackground: "#92a4ba",
      inputForeground: "#e2f5f8",
      placeholder: "#6c8ca0",
      disabledForeground: "#6c8ca0",
      buttonPrimaryBackground: "#1fd8ed",
      buttonPrimaryForeground: "#91b2d5",
      buttonSecondaryBackground: "#92a4ba",
      buttonSecondaryForeground: "#e2f5f8",
      link: "#4ebff1",
      focusRing: "#1fd8ed",
      selectionBackground: "#1fd8ed",
      selectionForeground: "#91b2d5",
      overlay: "rgba(13, 27, 42, 0.7)",
      glow: "rgba(0, 229, 255, 0.25)",
      }),
      code: { preset: 'glacial-ink', tokens: resolveCodeThemeTokens('glacial-ink', 'light') },
    },
    dark: {
      tokens: completeThemeTokens('dark', {
      accent: "#00e5ff",
      background: "#0d1b2a",
      surface: "#1b2838",
      surfaceElevated: "#2a3848",
      surfaceMuted: "#142232",
      border: "#3a4858",
      borderStrong: "#5a6878",
      textPrimary: "#e0f7fa",
      textSecondary: "#a0d0e0",
      textMuted: "#6088a0",
      foreground: "#e0f7fa",
      foregroundMuted: "#a0d0e0",
      foregroundSubtle: "#6088a0",
      accentHover: "#33ebff",
      accentForeground: "#0d1b2a",
      success: "#69f0ae",
      successForeground: "#0d1b2a",
      warning: "#ffd740",
      warningForeground: "#0d1b2a",
      danger: "#ff5252",
      dangerForeground: "#0d1b2a",
      info: "#40c4ff",
      inputBackground: "#2a3848",
      inputForeground: "#e0f7fa",
      placeholder: "#6088a0",
      disabledForeground: "#6088a0",
      buttonPrimaryBackground: "#00e5ff",
      buttonPrimaryForeground: "#0d1b2a",
      buttonSecondaryBackground: "#2a3848",
      buttonSecondaryForeground: "#e0f7fa",
      link: "#40c4ff",
      focusRing: "#00e5ff",
      selectionBackground: "#00e5ff",
      selectionForeground: "#0d1b2a",
      overlay: "rgba(13, 27, 42, 0.7)",
      glow: "rgba(0, 229, 255, 0.25)",
      }),
      code: { preset: 'glacial-ink', tokens: resolveCodeThemeTokens('glacial-ink', 'dark') },
    },
  },
};
