import { completeThemeTokens, type ThemeFamily } from '../themeTypes';

export const BUILTIN_MIDNIGHT_COBALT: ThemeFamily = {
  schemaVersion: 2,
  id: "midnight-cobalt",
  name: "Midnight Cobalt",
  aliases: ["builtin-midnight-cobalt","midnight-cobalt"],
  builtIn: true,
  variants: {
    light: {
      tokens: completeThemeTokens('light', {
      background: "#9daed6",
      surface: "#97a8cf",
      surfaceElevated: "#8ea1cb",
      border: "#8398bf",
      textPrimary: "#e8f0fd",
      textSecondary: "#98a8c3",
      textMuted: "#6f7f9a",
      accent: "#3b6ed4",
      accentHover: "#3972e1",
      accentForeground: "#ffffff",
      success: "#79cf80",
      warning: "#f09647",
      danger: "#d54a4a",
      info: "#598ee8",
      focusRing: "#3b6ed4",
      overlay: "rgba(0,0,0,0.65)",
      glow: "rgba(30, 92, 217, 0.3)",
      surfaceMuted: "#9cabd1",
      borderStrong: "#788db4",
      dangerForeground: "#ffffff",
      warningForeground: "#ffffff",
      successForeground: "#ffffff",
      }),
    },
    dark: {
      tokens: completeThemeTokens('dark', {
      background: "#070b14",
      surface: "#0f1626",
      surfaceElevated: "#17223b",
      border: "#2a3b5c",
      textPrimary: "#e6f0ff",
      textSecondary: "#94a7c7",
      textMuted: "#687b9c",
      accent: "#1e5cd9",
      accentHover: "#2a6df0",
      accentForeground: "#ffffff",
      success: "#1b5e20",
      warning: "#9e4a00",
      danger: "#b71c1c",
      info: "#4c8bf5",
      focusRing: "#1e5cd9",
      overlay: "rgba(0,0,0,0.65)",
      glow: "rgba(30, 92, 217, 0.3)",
      surfaceMuted: "#0b101c",
      borderStrong: "#3d527a",
      dangerForeground: "#ffffff",
      warningForeground: "#ffffff",
      successForeground: "#ffffff",
      }),
    },
  },
};
