import { completeThemeTokens, type ThemeFamily } from '../themeTypes';

export const BUILTIN_MIDNIGHT_VELVET: ThemeFamily = {
  schemaVersion: 2,
  id: "midnight-velvet",
  name: "Midnight Velvet",
  aliases: ["builtin-midnight-velvet"],
  builtIn: true,
  variants: {
    light: {
      tokens: completeThemeTokens('light', {
      accent: "#d6b7df",
      background: "#9caad2",
      surface: "#969ecb",
      surfaceElevated: "#9096c4",
      surfaceMuted: "#97a0ce",
      border: "#8e93b8",
      borderStrong: "#8488a5",
      textPrimary: "#f4e7e9",
      textSecondary: "#cebac1",
      textMuted: "#8f818f",
      foreground: "#f4e7e9",
      foregroundMuted: "#cebac1",
      foregroundSubtle: "#8f818f",
      accentHover: "#e6cbef",
      accentForeground: "#9caad2",
      success: "#a9d2aa",
      successForeground: "#9caad2",
      warning: "#f5ca8a",
      warningForeground: "#9caad2",
      danger: "#e9a0a0",
      dangerForeground: "#9caad2",
      info: "#98c9f1",
      inputBackground: "#9096c4",
      inputForeground: "#f4e7e9",
      placeholder: "#8f818f",
      disabledForeground: "#8f818f",
      buttonPrimaryBackground: "#d6b7df",
      buttonPrimaryForeground: "#9caad2",
      buttonSecondaryBackground: "#9096c4",
      buttonSecondaryForeground: "#f4e7e9",
      link: "#98c9f1",
      focusRing: "#d6b7df",
      selectionBackground: "#d6b7df",
      selectionForeground: "#9caad2",
      overlay: "rgba(10, 14, 26, 0.7)",
      glow: "rgba(216, 180, 226, 0.25)",
      }),
    },
    dark: {
      tokens: completeThemeTokens('dark', {
      accent: "#d8b4e2",
      background: "#0a0e1a",
      surface: "#14182e",
      surfaceElevated: "#1e2240",
      surfaceMuted: "#101428",
      border: "#2e3250",
      borderStrong: "#4e5270",
      textPrimary: "#f5e6e8",
      textSecondary: "#d0b8c0",
      textMuted: "#908090",
      foreground: "#f5e6e8",
      foregroundMuted: "#d0b8c0",
      foregroundSubtle: "#908090",
      accentHover: "#e8c8f2",
      accentForeground: "#0a0e1a",
      success: "#a5d6a7",
      successForeground: "#0a0e1a",
      warning: "#ffcc80",
      warningForeground: "#0a0e1a",
      danger: "#ef9a9a",
      dangerForeground: "#0a0e1a",
      info: "#90caf9",
      inputBackground: "#1e2240",
      inputForeground: "#f5e6e8",
      placeholder: "#908090",
      disabledForeground: "#908090",
      buttonPrimaryBackground: "#d8b4e2",
      buttonPrimaryForeground: "#0a0e1a",
      buttonSecondaryBackground: "#1e2240",
      buttonSecondaryForeground: "#f5e6e8",
      link: "#90caf9",
      focusRing: "#d8b4e2",
      selectionBackground: "#d8b4e2",
      selectionForeground: "#0a0e1a",
      overlay: "rgba(10, 14, 26, 0.7)",
      glow: "rgba(216, 180, 226, 0.25)",
      }),
    },
  },
};
