import { completeThemeTokens, type ThemeFamily } from '../themeTypes';

export const BUILTIN_MONOKAI: ThemeFamily = {
  schemaVersion: 2,
  id: "monokai",
  name: "Forge Monokai",
  aliases: ["builtin-monokai"],
  builtIn: true,
  variants: {
    light: {
      tokens: completeThemeTokens('light', {
      background: "#b2b4a9",
      surface: "#aeaea2",
      surfaceElevated: "#a7a69a",
      border: "#8f8f8f",
      textPrimary: "#f8f8f2",
      textSecondary: "#a4a28c",
      textMuted: "#969583",
      accent: "#a1d43c",
      accentHover: "#e93676",
      accentForeground: "#b2b4a9",
      success: "#a1d43c",
      warning: "#ddd47d",
      danger: "#ee296a",
      dangerForeground: "#ffffff",
      info: "#70d2e5",
      focusRing: "#a1d43c",
      overlay: "rgba(0, 0, 0, 0.6)",
      glow: "rgba(166, 226, 46, 0.25)",
      surfaceMuted: "#b1b2a7",
      borderStrong: "#f8f8f2",
      }),
    },
    dark: {
      tokens: completeThemeTokens('dark', {
      background: "#272822",
      surface: "#383830",
      surfaceElevated: "#49483e",
      border: "#6b6b6b",
      textPrimary: "#f8f8f2",
      textSecondary: "#a6a48a",
      textMuted: "#989681",
      accent: "#a6e22e",
      accentHover: "#f92672",
      accentForeground: "#272822",
      success: "#a6e22e",
      warning: "#e6db74",
      danger: "#e6004c",
      dangerForeground: "#ffffff",
      info: "#66d9ef",
      focusRing: "#a6e22e",
      overlay: "rgba(0, 0, 0, 0.6)",
      glow: "rgba(166, 226, 46, 0.25)",
      surfaceMuted: "#2c2d26",
      borderStrong: "#f8f8f2",
      }),
    },
  },
};
