import { completeThemeTokens, type ThemeFamily } from '../themeTypes';
import { resolveCodeThemeTokens } from '../codeSyntax';

export const BUILTIN_NEON_DUSK: ThemeFamily = {
  schemaVersion: 2,
  id: "neon-dusk",
  name: "Neon Dusk",
  aliases: ["builtin-neon-dusk"],
  builtIn: true,
  variants: {
    light: {
      tokens: completeThemeTokens('light', {
      accent: "#d053e2",
      background: "#a39ad1",
      surface: "#9e96c9",
      surfaceElevated: "#938ec3",
      surfaceMuted: "#9c97cc",
      border: "#8d87b8",
      borderStrong: "#7b75aa",
      textPrimary: "#f0eff4",
      textSecondary: "#cac6de",
      textMuted: "#918bad",
      foreground: "#f0eff4",
      foregroundMuted: "#cac6de",
      foregroundSubtle: "#918bad",
      accentHover: "#dc78eb",
      accentForeground: "#a39ad1",
      success: "#67dea2",
      successForeground: "#a39ad1",
      warning: "#e8c14f",
      warningForeground: "#a39ad1",
      danger: "#ea6f6f",
      dangerForeground: "#a39ad1",
      info: "#69d9ea",
      inputBackground: "#938ec3",
      inputForeground: "#f0eff4",
      placeholder: "#918bad",
      disabledForeground: "#918bad",
      buttonPrimaryBackground: "#d053e2",
      buttonPrimaryForeground: "#a39ad1",
      buttonSecondaryBackground: "#938ec3",
      buttonSecondaryForeground: "#f0eff4",
      link: "#69d9ea",
      focusRing: "#d053e2",
      selectionBackground: "#d053e2",
      selectionForeground: "#a39ad1",
      overlay: "rgba(15, 12, 31, 0.7)",
      glow: "rgba(217, 70, 239, 0.25)",
      }),
      code: { preset: 'neon-dusk', tokens: resolveCodeThemeTokens('neon-dusk', 'light') },
    },
    dark: {
      tokens: completeThemeTokens('dark', {
      accent: "#d946ef",
      background: "#0f0c1f",
      surface: "#1a1630",
      surfaceElevated: "#252146",
      surfaceMuted: "#14122a",
      border: "#36315c",
      borderStrong: "#544d88",
      textPrimary: "#f0eef5",
      textSecondary: "#c9c4e0",
      textMuted: "#8f88b0",
      foreground: "#f0eef5",
      foregroundMuted: "#c9c4e0",
      foregroundSubtle: "#8f88b0",
      accentHover: "#e46ef5",
      accentForeground: "#0f0c1f",
      success: "#5de8a2",
      successForeground: "#0f0c1f",
      warning: "#f5c842",
      warningForeground: "#0f0c1f",
      danger: "#f56464",
      dangerForeground: "#0f0c1f",
      info: "#5ee1f5",
      inputBackground: "#252146",
      inputForeground: "#f0eef5",
      placeholder: "#8f88b0",
      disabledForeground: "#8f88b0",
      buttonPrimaryBackground: "#d946ef",
      buttonPrimaryForeground: "#0f0c1f",
      buttonSecondaryBackground: "#252146",
      buttonSecondaryForeground: "#f0eef5",
      link: "#5ee1f5",
      focusRing: "#d946ef",
      selectionBackground: "#d946ef",
      selectionForeground: "#0f0c1f",
      overlay: "rgba(15, 12, 31, 0.7)",
      glow: "rgba(217, 70, 239, 0.25)",
      }),
      code: { preset: 'neon-dusk', tokens: resolveCodeThemeTokens('neon-dusk', 'dark') },
    },
  },
};
