import { completeThemeTokens, type ThemeFamily } from '../themeTypes';

export const BUILTIN_NORD: ThemeFamily = {
  schemaVersion: 2,
  id: "nord",
  name: "Forge Nord",
  aliases: ["builtin-nord"],
  builtIn: true,
  variants: {
    light: {
      tokens: completeThemeTokens('light', {
      background: "#9aa2b3",
      surface: "#929aad",
      surfaceElevated: "#8d96a9",
      border: "#8891a5",
      textPrimary: "#d9dee8",
      textSecondary: "#b2b9c4",
      textMuted: "#86a1bc",
      accent: "#8dbdcb",
      accentHover: "#92b9b8",
      accentForeground: "#9aa2b3",
      success: "#a3ba90",
      warning: "#e4c992",
      danger: "#f47676",
      info: "#86a1bc",
      focusRing: "#8dbdcb",
      overlay: "rgba(0, 0, 0, 0.6)",
      glow: "rgba(136, 192, 208, 0.25)",
      surfaceMuted: "#9da4b4",
      borderStrong: "#d9dee8",
      }),
    },
    dark: {
      tokens: completeThemeTokens('dark', {
      background: "#2E3440",
      surface: "#3B4252",
      surfaceElevated: "#434C5E",
      border: "#4C566A",
      textPrimary: "#D8DEE9",
      textSecondary: "#B0B9C6",
      textMuted: "#81A1C1",
      accent: "#88C0D0",
      accentHover: "#8FBCBB",
      accentForeground: "#2E3440",
      success: "#A3BE8C",
      warning: "#EBCB8B",
      danger: "#ff6b6b",
      info: "#81A1C1",
      focusRing: "#88C0D0",
      overlay: "rgba(0, 0, 0, 0.6)",
      glow: "rgba(136, 192, 208, 0.25)",
      surfaceMuted: "#2A2F3A",
      borderStrong: "#D8DEE9",
      }),
    },
  },
};
