import { completeThemeTokens, type ThemeFamily } from '../themeTypes';

export const BUILTIN_OBSIDIAN_EMBER: ThemeFamily = {
  schemaVersion: 2,
  id: "obsidian-ember",
  name: "Obsidian Ember",
  aliases: ["builtin-obsidian-ember","obsidian-ember"],
  builtIn: true,
  variants: {
    light: {
      tokens: completeThemeTokens('light', {
      background: "#b7b7b7",
      surface: "#b3b3b3",
      surfaceElevated: "#aeaeae",
      border: "#a8a8a8",
      textPrimary: "#e9e4da",
      textSecondary: "#9f9a91",
      textMuted: "#95908a",
      accent: "#e06b45",
      accentHover: "#e26b3d",
      accentForeground: "#ffffff",
      success: "#79cf80",
      warning: "#f09647",
      danger: "#d54a4a",
      info: "#8f877c",
      focusRing: "#d2653c",
      overlay: "rgba(0,0,0,0.7)",
      glow: "rgba(217, 83, 33, 0.25)",
      surfaceMuted: "#b5b5b5",
      borderStrong: "#9d9d9d",
      dangerForeground: "#ffffff",
      warningForeground: "#ffffff",
      successForeground: "#ffffff",
      }),
    },
    dark: {
      tokens: completeThemeTokens('dark', {
      background: "#121212",
      surface: "#1c1c1c",
      surfaceElevated: "#262626",
      border: "#333333",
      textPrimary: "#eae4d9",
      textSecondary: "#a09a90",
      textMuted: "#706b64",
      accent: "#b83a10",
      accentHover: "#f0642f",
      accentForeground: "#ffffff",
      success: "#1b5e20",
      warning: "#9e4a00",
      danger: "#b71c1c",
      info: "#8c8375",
      focusRing: "#d95321",
      overlay: "rgba(0,0,0,0.7)",
      glow: "rgba(217, 83, 33, 0.25)",
      surfaceMuted: "#161616",
      borderStrong: "#4c4c4c",
      dangerForeground: "#ffffff",
      warningForeground: "#ffffff",
      successForeground: "#ffffff",
      }),
    },
  },
};
