import { completeThemeTokens, type ThemeFamily } from '../themeTypes';
import { resolveCodeThemeTokens } from '../codeSyntax';

export const BUILTIN_OBSIDIAN_BLOOM: ThemeFamily = {
  schemaVersion: 2,
  id: "obsidian-bloom",
  name: "Obsidian Bloom",
  aliases: ["builtin-obsidian-bloom"],
  builtIn: true,
  variants: {
    light: {
      tokens: completeThemeTokens('light', {
      accent: "#d7758a",
      background: "#bda8ca",
      surface: "#baaabf",
      surfaceElevated: "#b3aab5",
      surfaceMuted: "#beadc1",
      border: "#afa1b2",
      borderStrong: "#a496a2",
      textPrimary: "#efe9ef",
      textSecondary: "#c7bbc7",
      textMuted: "#8e7e8e",
      foreground: "#efe9ef",
      foregroundMuted: "#c7bbc7",
      foregroundSubtle: "#8e7e8e",
      accentHover: "#e193a3",
      accentForeground: "#bda8ca",
      success: "#6ca36c",
      successForeground: "#bda8ca",
      warning: "#ca9d54",
      warningForeground: "#bda8ca",
      danger: "#db6666",
      dangerForeground: "#bda8ca",
      info: "#92b8e1",
      inputBackground: "#b3aab5",
      inputForeground: "#efe9ef",
      placeholder: "#8e7e8e",
      disabledForeground: "#8e7e8e",
      buttonPrimaryBackground: "#d7758a",
      buttonPrimaryForeground: "#bda8ca",
      buttonSecondaryBackground: "#b3aab5",
      buttonSecondaryForeground: "#efe9ef",
      link: "#92b8e1",
      focusRing: "#d7758a",
      selectionBackground: "#d7758a",
      selectionForeground: "#bda8ca",
      overlay: "rgba(15, 10, 18, 0.7)",
      glow: "rgba(224, 108, 133, 0.25)",
      }),
      code: { preset: 'obsidian-bloom', tokens: resolveCodeThemeTokens('obsidian-bloom', 'light') },
    },
    dark: {
      tokens: completeThemeTokens('dark', {
      accent: "#e06c85",
      background: "#0f0a12",
      surface: "#1a141c",
      surfaceElevated: "#252026",
      surfaceMuted: "#140f15",
      border: "#332a35",
      borderStrong: "#524550",
      textPrimary: "#f0e8f0",
      textSecondary: "#c8bac8",
      textMuted: "#8f7d8f",
      foreground: "#f0e8f0",
      foregroundMuted: "#c8bac8",
      foregroundSubtle: "#8f7d8f",
      accentHover: "#e88c9f",
      accentForeground: "#0f0a12",
      success: "#5a9e5a",
      successForeground: "#0f0a12",
      warning: "#d4a04a",
      warningForeground: "#0f0a12",
      danger: "#e55c5c",
      dangerForeground: "#0f0a12",
      info: "#8bb8e8",
      inputBackground: "#252026",
      inputForeground: "#f0e8f0",
      placeholder: "#8f7d8f",
      disabledForeground: "#8f7d8f",
      buttonPrimaryBackground: "#e06c85",
      buttonPrimaryForeground: "#0f0a12",
      buttonSecondaryBackground: "#252026",
      buttonSecondaryForeground: "#f0e8f0",
      link: "#8bb8e8",
      focusRing: "#e06c85",
      selectionBackground: "#e06c85",
      selectionForeground: "#0f0a12",
      overlay: "rgba(15, 10, 18, 0.7)",
      glow: "rgba(224, 108, 133, 0.25)",
      }),
      code: { preset: 'obsidian-bloom', tokens: resolveCodeThemeTokens('obsidian-bloom', 'dark') },
    },
  },
};
