import { completeThemeTokens, type ThemeFamily } from '../themeTypes';

export const BUILTIN_ONE_DARK: ThemeFamily = {
  schemaVersion: 2,
  id: "one-dark",
  name: "Forge One Dark",
  aliases: ["builtin-one-dark"],
  builtIn: true,
  variants: {
    light: {
      tokens: completeThemeTokens('light', {
      background: "#a1a7b4",
      surface: "#9aa1ae",
      surfaceElevated: "#949baa",
      border: "#8c93a4",
      textPrimary: "#acb2bd",
      textSecondary: "#9da0a9",
      textMuted: "#92969d",
      accent: "#6caee4",
      accentHover: "#5b8cc3",
      accentForeground: "#a1a7b4",
      success: "#99bd7f",
      warning: "#ddbe83",
      danger: "#d1414b",
      dangerForeground: "#ffffff",
      info: "#5eb0ba",
      focusRing: "#6caee4",
      overlay: "rgba(0, 0, 0, 0.6)",
      glow: "rgba(97, 175, 239, 0.25)",
      surfaceMuted: "#9ea5b2",
      borderStrong: "#acb2bd",
      }),
    },
    dark: {
      tokens: completeThemeTokens('dark', {
      background: "#282c34",
      surface: "#353b45",
      surfaceElevated: "#3e4451",
      border: "#4b5263",
      textPrimary: "#abb2bf",
      textSecondary: "#9ca0aa",
      textMuted: "#91969e",
      accent: "#61afef",
      accentHover: "#528bcc",
      accentForeground: "#282c34",
      success: "#98c379",
      warning: "#e5c07b",
      danger: "#cf222e",
      dangerForeground: "#ffffff",
      info: "#56b6c2",
      focusRing: "#61afef",
      overlay: "rgba(0, 0, 0, 0.6)",
      glow: "rgba(97, 175, 239, 0.25)",
      surfaceMuted: "#2c313a",
      borderStrong: "#abb2bf",
      }),
    },
  },
};
