import { completeThemeTokens, type ThemeFamily } from '../themeTypes';
import { resolveCodeThemeTokens } from '../codeSyntax';

export const BUILTIN_PORCELAIN_SKY: ThemeFamily = {
  schemaVersion: 2,
  id: "porcelain-sky",
  name: "Porcelain Sky",
  aliases: ["builtin-porcelain-sky","porcelain-sky"],
  builtIn: true,
  variants: {
    light: {
      tokens: completeThemeTokens('light', {
      background: "#f8fafc",
      surface: "#eff4f9",
      surfaceElevated: "#ffffff",
      border: "#cbd5e1",
      textPrimary: "#1e293b",
      textSecondary: "#475569",
      textMuted: "#64748b",
      accent: "#2563eb",
      accentHover: "#1d4ed8",
      accentForeground: "#ffffff",
      success: "#1b5e20",
      warning: "#9e4a00",
      danger: "#b71c1c",
      info: "#3b82f6",
      focusRing: "#3b82f6",
      overlay: "rgba(255,255,255,0.7)",
      glow: "rgba(37, 99, 235, 0.2)",
      surfaceMuted: "#e2e8f0",
      borderStrong: "#94a3b8",
      warningForeground: "#ffffff",
      successForeground: "#ffffff",
      dangerForeground: "#ffffff",
      }),
      code: { preset: 'porcelain-sky', tokens: resolveCodeThemeTokens('porcelain-sky', 'light') },
    },
    dark: {
      tokens: completeThemeTokens('dark', {
      background: "#2a425a",
      surface: "#294561",
      surfaceElevated: "#404040",
      border: "#3e5066",
      textPrimary: "#1f293a",
      textSecondary: "#495567",
      textMuted: "#667489",
      accent: "#1d54cd",
      accentHover: "#2652cf",
      accentForeground: "#404040",
      success: "#1e5b23",
      warning: "#964b08",
      danger: "#af2424",
      info: "#1458c8",
      focusRing: "#1458c8",
      overlay: "rgba(255,255,255,0.7)",
      glow: "rgba(37, 99, 235, 0.2)",
      surfaceMuted: "#35475f",
      borderStrong: "#55657b",
      warningForeground: "#404040",
      successForeground: "#404040",
      dangerForeground: "#404040",
      }),
      code: { preset: 'porcelain-sky', tokens: resolveCodeThemeTokens('porcelain-sky', 'dark') },
    },
  },
};
