import { completeThemeTokens, type ThemeFamily } from '../themeTypes';
import { resolveCodeThemeTokens } from '../codeSyntax';

export const BUILTIN_PORCELAIN_DAYBREAK: ThemeFamily = {
  schemaVersion: 2,
  id: "porcelain-daybreak",
  name: "Porcelain Daybreak",
  aliases: ["builtin-porcelain-daybreak"],
  builtIn: true,
  variants: {
    light: {
      tokens: completeThemeTokens('light', {
      accent: "#ffab91",
      background: "#fafafa",
      surface: "#f0f0f0",
      surfaceElevated: "#e6e6e6",
      surfaceMuted: "#f5f5f5",
      border: "#dcdcdc",
      borderStrong: "#bcbcbc",
      textPrimary: "#37474f",
      textSecondary: "#5a6a72",
      textMuted: "#6b7d85",
      foreground: "#37474f",
      foregroundMuted: "#5a6a72",
      foregroundSubtle: "#6b7d85",
      accentHover: "#f59580",
      accentForeground: "#37474f",
      success: "#2e7d32",
      successForeground: "#ffffff",
      warning: "#ffb74d",
      warningForeground: "#37474f",
      danger: "#d32f2f",
      dangerForeground: "#ffffff",
      info: "#64b5f6",
      inputBackground: "#e6e6e6",
      inputForeground: "#37474f",
      placeholder: "#6b7d85",
      disabledForeground: "#6b7d85",
      buttonPrimaryBackground: "#ffab91",
      buttonPrimaryForeground: "#37474f",
      buttonSecondaryBackground: "#e6e6e6",
      buttonSecondaryForeground: "#37474f",
      link: "#64b5f6",
      focusRing: "#a84a39",
      selectionBackground: "#ffab91",
      selectionForeground: "#37474f",
      overlay: "rgba(55, 71, 79, 0.25)",
      glow: "rgba(255, 171, 145, 0.18)",
      }),
      code: { preset: 'porcelain-daybreak', tokens: resolveCodeThemeTokens('porcelain-daybreak', 'light') },
    },
    dark: {
      tokens: completeThemeTokens('dark', {
      accent: "#a82f09",
      background: "#424242",
      surface: "#474747",
      surfaceElevated: "#4b4b4b",
      surfaceMuted: "#444444",
      border: "#4f4f4f",
      borderStrong: "#5e5e5e",
      textPrimary: "#38474e",
      textSecondary: "#5b6a71",
      textMuted: "#6c7c84",
      foreground: "#38474e",
      foregroundMuted: "#5b6a71",
      foregroundSubtle: "#6c7c84",
      accentHover: "#a73016",
      accentForeground: "#38474e",
      success: "#327936",
      successForeground: "#404040",
      warning: "#c57a0a",
      warningForeground: "#38474e",
      danger: "#bf3232",
      dangerForeground: "#404040",
      info: "#146db5",
      inputBackground: "#4b4b4b",
      inputForeground: "#38474e",
      placeholder: "#6c7c84",
      disabledForeground: "#6c7c84",
      buttonPrimaryBackground: "#a82f09",
      buttonPrimaryForeground: "#38474e",
      buttonSecondaryBackground: "#4b4b4b",
      buttonSecondaryForeground: "#38474e",
      link: "#146db5",
      focusRing: "#a24e3f",
      selectionBackground: "#a82f09",
      selectionForeground: "#38474e",
      overlay: "rgba(55, 71, 79, 0.25)",
      glow: "rgba(255, 171, 145, 0.18)",
      }),
      code: { preset: 'porcelain-daybreak', tokens: resolveCodeThemeTokens('porcelain-daybreak', 'dark') },
    },
  },
};
