import { completeThemeTokens, type ThemeFamily } from '../themeTypes';
import { resolveCodeThemeTokens } from '../codeSyntax';

export const BUILTIN_ROSEPINE: ThemeFamily = {
  schemaVersion: 2,
  id: "rosepine",
  name: "Rosepine",
  aliases: ["builtin-rosepine"],
  builtIn: true,
  variants: {
    light: {
      tokens: completeThemeTokens('light', {
      background: "#a8a4c0",
      surface: "#a29fbe",
      surfaceElevated: "#9d99bc",
      border: "#9793ab",
      textPrimary: "#e1e0f2",
      textSecondary: "#928ea8",
      textMuted: "#817e95",
      accent: "#e7bfbe",
      accentHover: "#68a7c1",
      accentForeground: "#a8a4c0",
      success: "#a1ccd4",
      warning: "#ecbf81",
      danger: "#e27896",
      info: "#c4ace2",
      focusRing: "#e7bfbe",
      overlay: "rgba(25, 23, 36, 0.7)",
      glow: "rgba(235, 188, 186, 0.2)",
      surfaceMuted: "#a29fbc",
      borderStrong: "#817e95",
      }),
      code: { preset: 'rosepine', tokens: resolveCodeThemeTokens('rosepine', 'light') },
    },
    dark: {
      tokens: completeThemeTokens('dark', {
      background: "#191724",
      surface: "#1f1d2e",
      surfaceElevated: "#26233a",
      border: "#403d52",
      textPrimary: "#e0def4",
      textSecondary: "#908caa",
      textMuted: "#6e6a86",
      accent: "#ebbcba",
      accentHover: "#31748f",
      accentForeground: "#191724",
      success: "#9ccfd8",
      warning: "#f6c177",
      danger: "#eb6f92",
      info: "#c4a7e7",
      focusRing: "#ebbcba",
      overlay: "rgba(25, 23, 36, 0.7)",
      glow: "rgba(235, 188, 186, 0.2)",
      surfaceMuted: "#211f30",
      borderStrong: "#6e6a86",
      }),
      code: { preset: 'rosepine', tokens: resolveCodeThemeTokens('rosepine', 'dark') },
    },
  },
};
