import { completeThemeTokens, type ThemeFamily } from '../themeTypes';
import { resolveCodeThemeTokens } from '../codeSyntax';

export const BUILTIN_SAKURA_TERMINAL: ThemeFamily = {
  schemaVersion: 2,
  id: "sakura-terminal",
  name: "Sakura Terminal",
  aliases: ["builtin-sakura-terminal"],
  builtIn: true,
  variants: {
    light: {
      tokens: completeThemeTokens('light', {
      accent: "#f797a8",
      background: "#c1aabb",
      surface: "#b8a5b4",
      surfaceElevated: "#aea0ac",
      surfaceMuted: "#bba9b6",
      border: "#ab98a9",
      borderStrong: "#9b8c99",
      textPrimary: "#fde6ed",
      textSecondary: "#d1b3c0",
      textMuted: "#987c8a",
      foreground: "#fde6ed",
      foregroundMuted: "#d1b3c0",
      foregroundSubtle: "#987c8a",
      accentHover: "#f9b9c5",
      accentForeground: "#c1aabb",
      success: "#ade1ce",
      successForeground: "#c1aabb",
      warning: "#fad4bb",
      warningForeground: "#c1aabb",
      danger: "#f6949b",
      dangerForeground: "#c1aabb",
      info: "#cad0e7",
      inputBackground: "#aea0ac",
      inputForeground: "#fde6ed",
      placeholder: "#987c8a",
      disabledForeground: "#987c8a",
      buttonPrimaryBackground: "#f797a8",
      buttonPrimaryForeground: "#c1aabb",
      buttonSecondaryBackground: "#aea0ac",
      buttonSecondaryForeground: "#fde6ed",
      link: "#cad0e7",
      focusRing: "#f797a8",
      selectionBackground: "#f797a8",
      selectionForeground: "#c1aabb",
      overlay: "rgba(26, 18, 24, 0.7)",
      glow: "rgba(255, 143, 163, 0.25)",
      }),
      code: { preset: 'sakura-terminal', tokens: resolveCodeThemeTokens('sakura-terminal', 'light') },
    },
    dark: {
      tokens: completeThemeTokens('dark', {
      accent: "#ff8fa3",
      background: "#1a1218",
      surface: "#2a2028",
      surfaceElevated: "#3a3038",
      surfaceMuted: "#221a20",
      border: "#4a3a48",
      borderStrong: "#6a5a68",
      textPrimary: "#ffe4ec",
      textSecondary: "#d4b0c0",
      textMuted: "#9a7a8a",
      foreground: "#ffe4ec",
      foregroundMuted: "#d4b0c0",
      foregroundSubtle: "#9a7a8a",
      accentHover: "#ffb3c1",
      accentForeground: "#1a1218",
      success: "#a8e6cf",
      successForeground: "#1a1218",
      warning: "#ffd3b6",
      warningForeground: "#1a1218",
      danger: "#ff8b94",
      dangerForeground: "#1a1218",
      info: "#c7ceea",
      inputBackground: "#3a3038",
      inputForeground: "#ffe4ec",
      placeholder: "#9a7a8a",
      disabledForeground: "#9a7a8a",
      buttonPrimaryBackground: "#ff8fa3",
      buttonPrimaryForeground: "#1a1218",
      buttonSecondaryBackground: "#3a3038",
      buttonSecondaryForeground: "#ffe4ec",
      link: "#c7ceea",
      focusRing: "#ff8fa3",
      selectionBackground: "#ff8fa3",
      selectionForeground: "#1a1218",
      overlay: "rgba(26, 18, 24, 0.7)",
      glow: "rgba(255, 143, 163, 0.25)",
      }),
      code: { preset: 'sakura-terminal', tokens: resolveCodeThemeTokens('sakura-terminal', 'dark') },
    },
  },
};
