import { completeThemeTokens, type ThemeFamily } from '../themeTypes';
import { resolveCodeThemeTokens } from '../codeSyntax';

export const BUILTIN_SANDSTONE: ThemeFamily = {
  schemaVersion: 2,
  id: "sandstone",
  name: "Sandstone",
  aliases: ["builtin-sandstone","sandstone"],
  builtIn: true,
  variants: {
    light: {
      tokens: completeThemeTokens('light', {
      background: "#fcfaf8",
      surface: "#f3ece4",
      surfaceElevated: "#faf7f2",
      border: "#d6cec4",
      textPrimary: "#3d3935",
      textSecondary: "#66605a",
      textMuted: "#8a837c",
      accent: "#b85c3b",
      accentHover: "#9c4b2e",
      accentForeground: "#ffffff",
      success: "#1b5e20",
      warning: "#9e4a00",
      danger: "#b71c1c",
      info: "#826e5d",
      focusRing: "#b85c3b",
      overlay: "rgba(252,250,248,0.75)",
      glow: "rgba(184, 92, 59, 0.2)",
      surfaceMuted: "#e6ded5",
      borderStrong: "#b5aca1",
      warningForeground: "#ffffff",
      successForeground: "#ffffff",
      dangerForeground: "#ffffff",
      }),
      code: { preset: 'sandstone', tokens: resolveCodeThemeTokens('sandstone', 'light') },
    },
    dark: {
      tokens: completeThemeTokens('dark', {
      background: "#5a422a",
      surface: "#624a2f",
      surfaceElevated: "#5f4b29",
      border: "#645848",
      textPrimary: "#3d3935",
      textSecondary: "#65605b",
      textMuted: "#7e7871",
      accent: "#b25f41",
      accentHover: "#974e34",
      accentForeground: "#404040",
      success: "#1e5b23",
      warning: "#964b08",
      danger: "#af2424",
      info: "#806e5f",
      focusRing: "#b25f41",
      overlay: "rgba(252,250,248,0.75)",
      glow: "rgba(184, 92, 59, 0.2)",
      surfaceMuted: "#61503d",
      borderStrong: "#70675b",
      warningForeground: "#404040",
      successForeground: "#404040",
      dangerForeground: "#404040",
      }),
      code: { preset: 'sandstone', tokens: resolveCodeThemeTokens('sandstone', 'dark') },
    },
  },
};
