import { completeThemeTokens, type ThemeFamily } from '../themeTypes';
import { resolveCodeThemeTokens } from '../codeSyntax';

export const BUILTIN_SWEET_NIGHTMARE: ThemeFamily = {
  schemaVersion: 2,
  id: "sweet-nightmare",
  name: "Sweet Nightmare",
  aliases: ["builtin-sweet-nightmare","sweet-nightmare"],
  builtIn: true,
  variants: {
    light: {
      tokens: completeThemeTokens('light', {
      accent: "#90c3cb",
      background: "#b8a7bd",
      surface: "#b5a0ba",
      surfaceElevated: "#b797ad",
      surfaceMuted: "#b29cb7",
      border: "#94899b",
      borderStrong: "#8f7895",
      textPrimary: "#f2edec",
      textSecondary: "#ccbfc8",
      textMuted: "#baa9b5",
      foreground: "#f2edec",
      foregroundMuted: "#ccbfc8",
      foregroundSubtle: "#baa9b5",
      accentHover: "#a6d0d8",
      accentForeground: "#bda7c3",
      success: "#85c9a9",
      successForeground: "#bda7c3",
      warning: "#e8b888",
      warningForeground: "#bda7c3",
      danger: "#e77ca1",
      dangerForeground: "#bda7c3",
      info: "#b799c4",
      inputBackground: "#b29cb7",
      inputForeground: "#f2edec",
      placeholder: "#baa9b5",
      disabledForeground: "#978693",
      buttonPrimaryBackground: "#90c3cb",
      buttonPrimaryForeground: "#bda7c3",
      buttonSecondaryBackground: "#b797ad",
      buttonSecondaryForeground: "#f2edec",
      link: "#90c3cb",
      focusRing: "#da91b0",
      selectionBackground: "#af87a5",
      selectionForeground: "#f2edec",
      overlay: "rgba(33, 25, 35, 0.75)",
      glow: "rgba(139, 199, 208, 0.25)",
      }),
      code: { preset: 'sweet-nightmare', tokens: resolveCodeThemeTokens('sweet-nightmare', 'light') },
    },
    dark: {
      tokens: completeThemeTokens('dark', {
      accent: "#8BC7D0",
      background: "#211923",
      surface: "#2D2130",
      surfaceElevated: "#412A3A",
      surfaceMuted: "#37283A",
      border: "#675B6E",
      borderStrong: "#8A6D91",
      textPrimary: "#F3EDEB",
      textSecondary: "#CDBEC9",
      textMuted: "#BBA7B6",
      foreground: "#F3EDEB",
      foregroundMuted: "#CDBEC9",
      foregroundSubtle: "#BBA7B6",
      accentHover: "#A2D3DC",
      accentForeground: "#1A121C",
      success: "#7FCFA9",
      successForeground: "#1A121C",
      warning: "#F0B880",
      warningForeground: "#1A121C",
      danger: "#F0739E",
      dangerForeground: "#1A121C",
      info: "#B995C8",
      inputBackground: "#37283A",
      inputForeground: "#F3EDEB",
      placeholder: "#BBA7B6",
      disabledForeground: "#988494",
      buttonPrimaryBackground: "#8BC7D0",
      buttonPrimaryForeground: "#1A121C",
      buttonSecondaryBackground: "#412A3A",
      buttonSecondaryForeground: "#F3EDEB",
      link: "#8BC7D0",
      focusRing: "#E18AAF",
      selectionBackground: "#633D59",
      selectionForeground: "#F3EDEB",
      overlay: "rgba(33, 25, 35, 0.75)",
      glow: "rgba(139, 199, 208, 0.25)",
      }),
      code: { preset: 'sweet-nightmare', tokens: resolveCodeThemeTokens('sweet-nightmare', 'dark') },
    },
  },
};
