import { completeThemeTokens, type ThemeFamily } from '../themeTypes';

export const BUILTIN_SYNTHWAVE_HARBOR: ThemeFamily = {
  schemaVersion: 2,
  id: "synthwave-harbor",
  name: "Synthwave Harbor",
  aliases: ["builtin-synthwave-harbor"],
  builtIn: true,
  variants: {
    light: {
      tokens: completeThemeTokens('light', {
      accent: "#f36da7",
      background: "#97a7d5",
      surface: "#95a3cc",
      surfaceElevated: "#8e9bc7",
      surfaceMuted: "#94a5d2",
      border: "#8d97ba",
      borderStrong: "#848ba6",
      textPrimary: "#e2f5f8",
      textSecondary: "#acc7d4",
      textMuted: "#6c879c",
      foreground: "#e2f5f8",
      foregroundMuted: "#acc7d4",
      foregroundSubtle: "#6c879c",
      accentHover: "#f58ab9",
      accentForeground: "#97a7d5",
      success: "#29ee8e",
      successForeground: "#97a7d5",
      warning: "#eddc1f",
      warningForeground: "#97a7d5",
      danger: "#f25f5f",
      dangerForeground: "#97a7d5",
      info: "#1faded",
      inputBackground: "#8e9bc7",
      inputForeground: "#e2f5f8",
      placeholder: "#6c879c",
      disabledForeground: "#6c879c",
      buttonPrimaryBackground: "#f36da7",
      buttonPrimaryForeground: "#97a7d5",
      buttonSecondaryBackground: "#8e9bc7",
      buttonSecondaryForeground: "#e2f5f8",
      link: "#1faded",
      focusRing: "#f36da7",
      selectionBackground: "#f36da7",
      selectionForeground: "#97a7d5",
      overlay: "rgba(10, 15, 30, 0.7)",
      glow: "rgba(255, 97, 166, 0.25)",
      }),
    },
    dark: {
      tokens: completeThemeTokens('dark', {
      accent: "#ff61a6",
      background: "#0a0f1e",
      surface: "#131a2e",
      surfaceElevated: "#1c2440",
      surfaceMuted: "#0e1528",
      border: "#2c3450",
      borderStrong: "#4c5470",
      textPrimary: "#e0f7fa",
      textSecondary: "#a8c8d8",
      textMuted: "#6888a0",
      foreground: "#e0f7fa",
      foregroundMuted: "#a8c8d8",
      foregroundSubtle: "#6888a0",
      accentHover: "#ff80b8",
      accentForeground: "#0a0f1e",
      success: "#00e676",
      successForeground: "#0a0f1e",
      warning: "#ffea00",
      warningForeground: "#0a0f1e",
      danger: "#ff5252",
      dangerForeground: "#0a0f1e",
      info: "#00b0ff",
      inputBackground: "#1c2440",
      inputForeground: "#e0f7fa",
      placeholder: "#6888a0",
      disabledForeground: "#6888a0",
      buttonPrimaryBackground: "#ff61a6",
      buttonPrimaryForeground: "#0a0f1e",
      buttonSecondaryBackground: "#1c2440",
      buttonSecondaryForeground: "#e0f7fa",
      link: "#00b0ff",
      focusRing: "#ff61a6",
      selectionBackground: "#ff61a6",
      selectionForeground: "#0a0f1e",
      overlay: "rgba(10, 15, 30, 0.7)",
      glow: "rgba(255, 97, 166, 0.25)",
      }),
    },
  },
};
