import { completeThemeTokens, type ThemeFamily } from '../themeTypes';

export const BUILTIN_TERMINAL_FOREST: ThemeFamily = {
  schemaVersion: 2,
  id: "terminal-forest",
  name: "Terminal Forest",
  aliases: ["builtin-terminal-forest","terminal-forest"],
  builtIn: true,
  variants: {
    light: {
      tokens: completeThemeTokens('light', {
      background: "#a5cdb3",
      surface: "#9ec9ae",
      surfaceElevated: "#98c4a8",
      border: "#8ebe9f",
      textPrimary: "#d9e7de",
      textSecondary: "#8da496",
      textMuted: "#829b8c",
      accent: "#51c77a",
      accentHover: "#66e292",
      accentForeground: "#bfbfbf",
      success: "#79cf80",
      warning: "#f09647",
      danger: "#d54a4a",
      info: "#62a77b",
      focusRing: "#51c77a",
      overlay: "rgba(0,0,0,0.7)",
      glow: "rgba(71, 209, 119, 0.25)",
      surfaceMuted: "#a2cbaf",
      borderStrong: "#82b694",
      dangerForeground: "#ffffff",
      warningForeground: "#ffffff",
      successForeground: "#ffffff",
      }),
    },
    dark: {
      tokens: completeThemeTokens('dark', {
      background: "#09120c",
      surface: "#112217",
      surfaceElevated: "#1a3323",
      border: "#264a33",
      textPrimary: "#d8e8de",
      textSecondary: "#8ba696",
      textMuted: "#5e7a69",
      accent: "#47d177",
      accentHover: "#5bed8f",
      accentForeground: "#000000",
      success: "#1b5e20",
      warning: "#9e4a00",
      danger: "#b71c1c",
      info: "#5cad79",
      focusRing: "#47d177",
      overlay: "rgba(0,0,0,0.7)",
      glow: "rgba(71, 209, 119, 0.25)",
      surfaceMuted: "#0d1a11",
      borderStrong: "#366646",
      dangerForeground: "#ffffff",
      warningForeground: "#ffffff",
      successForeground: "#ffffff",
      }),
    },
  },
};
