import { completeThemeTokens, type ThemeFamily } from '../themeTypes';
import { resolveCodeThemeTokens } from '../codeSyntax';

export const BUILTIN_TOKYO_NIGHT: ThemeFamily = {
  schemaVersion: 2,
  id: "tokyo-night",
  name: "Forge Tokyo",
  aliases: ["builtin-tokyo-night"],
  builtIn: true,
  variants: {
    light: {
      tokens: completeThemeTokens('light', {
      background: "#a4a6bd",
      surface: "#989ebb",
      surfaceElevated: "#8f95b2",
      border: "#777fa3",
      textPrimary: "#acb3d3",
      textSecondary: "#9ea7ca",
      textMuted: "#838aa8",
      accent: "#83a5ee",
      accentHover: "#bda1f0",
      accentForeground: "#a4a6bd",
      success: "#9ec772",
      warning: "#d7ad71",
      danger: "#ed8094",
      info: "#87ccf5",
      focusRing: "#83a5ee",
      overlay: "rgba(0, 0, 0, 0.6)",
      glow: "rgba(122, 162, 247, 0.25)",
      surfaceMuted: "#9aa1bf",
      borderStrong: "#acb3d3",
      }),
      code: { preset: 'tokyo-night', tokens: resolveCodeThemeTokens('tokyo-night', 'light') },
    },
    dark: {
      tokens: completeThemeTokens('dark', {
      background: "#1a1b26",
      surface: "#24283b",
      surfaceElevated: "#363b54",
      border: "#565f89",
      textPrimary: "#a9b1d6",
      textSecondary: "#9aa5ce",
      textMuted: "#8088ab",
      accent: "#7aa2f7",
      accentHover: "#bb9af7",
      accentForeground: "#1a1b26",
      success: "#9ece6a",
      warning: "#e0af68",
      danger: "#f7768e",
      info: "#7dcfff",
      focusRing: "#7aa2f7",
      overlay: "rgba(0, 0, 0, 0.6)",
      glow: "rgba(122, 162, 247, 0.25)",
      surfaceMuted: "#1f2335",
      borderStrong: "#a9b1d6",
      }),
      code: { preset: 'tokyo-night', tokens: resolveCodeThemeTokens('tokyo-night', 'dark') },
    },
  },
};
