import { completeThemeTokens, type ThemeFamily } from '../themeTypes';
import { resolveCodeThemeTokens } from '../codeSyntax';

export const BUILTIN_TOXIC_LIMEWIRE: ThemeFamily = {
  schemaVersion: 2,
  id: "toxic-limewire",
  name: "Toxic Limewire",
  aliases: ["builtin-toxic-limewire"],
  builtIn: true,
  variants: {
    light: {
      tokens: completeThemeTokens('light', {
      accent: "#bfed1f",
      background: "#afc0b2",
      surface: "#adbda7",
      surfaceElevated: "#a9b6a1",
      surfaceMuted: "#afc3a7",
      border: "#a3b198",
      borderStrong: "#959f8d",
      textPrimary: "#e9f4ea",
      textSecondary: "#b9ceb2",
      textMuted: "#7f9379",
      foreground: "#e9f4ea",
      foregroundMuted: "#b9ceb2",
      foregroundSubtle: "#7f9379",
      accentHover: "#d0f14e",
      accentForeground: "#afc0b2",
      success: "#7ced1e",
      successForeground: "#afc0b2",
      warning: "#eddc1f",
      warningForeground: "#afc0b2",
      danger: "#ee284f",
      dangerForeground: "#afc0b2",
      info: "#1fd8ed",
      inputBackground: "#a9b6a1",
      inputForeground: "#e9f4ea",
      placeholder: "#7f9379",
      disabledForeground: "#7f9379",
      buttonPrimaryBackground: "#bfed1f",
      buttonPrimaryForeground: "#afc0b2",
      buttonSecondaryBackground: "#a9b6a1",
      buttonSecondaryForeground: "#e9f4ea",
      link: "#1fd8ed",
      focusRing: "#bfed1f",
      selectionBackground: "#bfed1f",
      selectionForeground: "#afc0b2",
      overlay: "rgba(15, 20, 16, 0.7)",
      glow: "rgba(198, 255, 0, 0.25)",
      }),
      code: { preset: 'toxic-limewire', tokens: resolveCodeThemeTokens('toxic-limewire', 'light') },
    },
    dark: {
      tokens: completeThemeTokens('dark', {
      accent: "#c6ff00",
      background: "#0f1410",
      surface: "#1c2319",
      surfaceElevated: "#2a3225",
      surfaceMuted: "#151c12",
      border: "#3a4532",
      borderStrong: "#5a6552",
      textPrimary: "#e8f5e9",
      textSecondary: "#b8d0b0",
      textMuted: "#789070",
      foreground: "#e8f5e9",
      foregroundMuted: "#b8d0b0",
      foregroundSubtle: "#789070",
      accentHover: "#d8ff40",
      accentForeground: "#0f1410",
      success: "#76ff03",
      successForeground: "#0f1410",
      warning: "#ffea00",
      warningForeground: "#0f1410",
      danger: "#ff1744",
      dangerForeground: "#0f1410",
      info: "#00e5ff",
      inputBackground: "#2a3225",
      inputForeground: "#e8f5e9",
      placeholder: "#789070",
      disabledForeground: "#789070",
      buttonPrimaryBackground: "#c6ff00",
      buttonPrimaryForeground: "#0f1410",
      buttonSecondaryBackground: "#2a3225",
      buttonSecondaryForeground: "#e8f5e9",
      link: "#00e5ff",
      focusRing: "#c6ff00",
      selectionBackground: "#c6ff00",
      selectionForeground: "#0f1410",
      overlay: "rgba(15, 20, 16, 0.7)",
      glow: "rgba(198, 255, 0, 0.25)",
      }),
      code: { preset: 'toxic-limewire', tokens: resolveCodeThemeTokens('toxic-limewire', 'dark') },
    },
  },
};
