import { completeThemeTokens, type ThemeFamily } from '../themeTypes';

export const BUILTIN_ULTRAVIOLET_RAIN: ThemeFamily = {
  schemaVersion: 2,
  id: "ultraviolet-rain",
  name: "Ultraviolet Rain",
  aliases: ["builtin-ultraviolet-rain"],
  builtIn: true,
  variants: {
    light: {
      tokens: completeThemeTokens('light', {
      accent: "#946ff3",
      background: "#b0aac3",
      surface: "#a49cc2",
      surfaceElevated: "#9c97b9",
      surfaceMuted: "#9c94cc",
      border: "#938db1",
      borderStrong: "#827da0",
      textPrimary: "#ede8f5",
      textSecondary: "#c5bbdd",
      textMuted: "#8c83a5",
      foreground: "#ede8f5",
      foregroundMuted: "#c5bbdd",
      foregroundSubtle: "#8c83a5",
      accentHover: "#a387f5",
      accentForeground: "#b0aac3",
      success: "#bef1cc",
      successForeground: "#b0aac3",
      warning: "#f5df89",
      warningForeground: "#b0aac3",
      danger: "#f5928a",
      dangerForeground: "#b0aac3",
      info: "#8ad4f5",
      inputBackground: "#9c97b9",
      inputForeground: "#ede8f5",
      placeholder: "#8c83a5",
      disabledForeground: "#8c83a5",
      buttonPrimaryBackground: "#946ff3",
      buttonPrimaryForeground: "#b0aac3",
      buttonSecondaryBackground: "#9c97b9",
      buttonSecondaryForeground: "#ede8f5",
      link: "#8ad4f5",
      focusRing: "#946ff3",
      selectionBackground: "#946ff3",
      selectionForeground: "#b0aac3",
      overlay: "rgba(18, 16, 24, 0.7)",
      glow: "rgba(143, 99, 255, 0.25)",
      }),
    },
    dark: {
      tokens: completeThemeTokens('dark', {
      accent: "#8f63ff",
      background: "#121018",
      surface: "#1e1a2e",
      surfaceElevated: "#2c2840",
      surfaceMuted: "#181430",
      border: "#3e3858",
      borderStrong: "#5e5880",
      textPrimary: "#ede7f6",
      textSecondary: "#c4b8e0",
      textMuted: "#8a80a8",
      foreground: "#ede7f6",
      foregroundMuted: "#c4b8e0",
      foregroundSubtle: "#8a80a8",
      accentHover: "#9e7dff",
      accentForeground: "#121018",
      success: "#b9f6ca",
      successForeground: "#121018",
      warning: "#ffe57f",
      warningForeground: "#121018",
      danger: "#ff8a80",
      dangerForeground: "#121018",
      info: "#80d8ff",
      inputBackground: "#2c2840",
      inputForeground: "#ede7f6",
      placeholder: "#8a80a8",
      disabledForeground: "#8a80a8",
      buttonPrimaryBackground: "#8f63ff",
      buttonPrimaryForeground: "#121018",
      buttonSecondaryBackground: "#2c2840",
      buttonSecondaryForeground: "#ede7f6",
      link: "#80d8ff",
      focusRing: "#8f63ff",
      selectionBackground: "#8f63ff",
      selectionForeground: "#121018",
      overlay: "rgba(18, 16, 24, 0.7)",
      glow: "rgba(143, 99, 255, 0.25)",
      }),
    },
  },
};
