import { completeThemeTokens, type ThemeFamily } from '../themeTypes';

export const BUILTIN_VENICE: ThemeFamily = {
  schemaVersion: 2,
  id: "venice",
  name: "Venice Parity Dark",
  aliases: ["builtin-venice"],
  builtIn: true,
  variants: {
    light: {
      tokens: completeThemeTokens('light', {
      background: "#9ebbd8",
      surface: "#9ebbd4",
      surfaceElevated: "#9eb3c9",
      border: "#99adc3",
      textPrimary: "#dadee4",
      textSecondary: "#a5adb8",
      textMuted: "#7c8692",
      accent: "#6db1e3",
      accentHover: "#548dc8",
      accentForeground: "#9ebbd8",
      success: "#7bce72",
      warning: "#cca559",
      danger: "#e25151",
      info: "#87aaf5",
      focusRing: "#6db1e3",
      overlay: "rgba(5, 10, 15, 0.7)",
      glow: "rgba(99, 179, 237, 0.1)",
      surfaceMuted: "#9db7d1",
      borderStrong: "#7f8996",
      }),
    },
    dark: {
      tokens: completeThemeTokens('dark', {
      background: "#050a0f",
      surface: "#080f15",
      surfaceElevated: "#111922",
      border: "#1b2632",
      textPrimary: "#d9dee5",
      textSecondary: "#a3adba",
      textMuted: "#7a8694",
      accent: "#63b3ed",
      accentHover: "#2b6cb0",
      accentForeground: "#050a0f",
      success: "#74d66a",
      warning: "#d6a84f",
      danger: "#ef4444",
      info: "#7da7ff",
      focusRing: "#63b3ed",
      overlay: "rgba(5, 10, 15, 0.7)",
      glow: "rgba(99, 179, 237, 0.1)",
      surfaceMuted: "#0b131b",
      borderStrong: "#687483",
      }),
    },
  },
};
